version: 2

jobs:
  build:
    docker: 
      - image: circleci/golang:1.11.2
    steps:
      - checkout
      - restore_cache:
          key: cache1-{{ checksum "go.sum" }}
      - run: go build
      - run: go test ./...
      - save_cache:
          key: cache1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"